import Head from "next/head";

export default function HeadComponent({ title }: { title?: string }) {
    return (
        <Head>
            <title>{title ? `${title} - Frederik` : "Frederik"}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}
